GET http://localhost:4000/diary

###

GET http://localhost:4000/diary/682d6cf06513fe180b5b7215

###

POST http://localhost:4000/diary
Content-Type: application/json

{
  "title": "이제 마지막 시간",
  "content" : "데이터베이스에 일기 추가하기 츄라이~츄라이~"
}

###

PATCH http://localhost:4000/diary/682d6cf06513fe180b5b7215
Content-Type: application/json

{
  "title": "패치도 디비 연결결"
}

###

DELETE http://localhost:4000/diary/682d6cf06513fe180b5b7215
